# Generated by Django 4.0.5 on 2022-06-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='emergency',
            new_name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_image',
            field=models.ImageField(default='default.png', upload_to='hood-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Nairobi', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default='Nairobi Hood', on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.neighbourhood'),
        ),
    ]
