# Generated by Django 4.0.5 on 2022-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='person.jpeg', upload_to='images/'),
        ),
    ]
