# Generated by Django 4.0.5 on 2022-06-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_rename_decription_neighbourhood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.neighbourhood'),
        ),
    ]
