# Generated by Django 4.0.5 on 2022-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='hood_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
