# Generated by Django 4.0.5 on 2022-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_rename_decription_neighbourhood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hood_images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
